from pygame import USEREVENT, event

# just defining a bunch of event names nothing special going on here

SINGLE_LINE = USEREVENT + 1
DOUBLE_LINE = USEREVENT + 2
TRIPLE_LINE = USEREVENT + 3
TETRIS_LINE = USEREVENT + 4
SPIN = USEREVENT + 10
MINI_SPIN = USEREVENT + 11
MINI_SINGLE_SPIN = USEREVENT + 12
SINGLE_SPIN = USEREVENT + 13
DOUBLE_SPIN = USEREVENT + 14
TRIPLE_SPIN = USEREVENT + 15
SINGLE_CLEAR = USEREVENT + 20
DOUBLE_CLEAR = USEREVENT + 21
TRIPLE_CLEAR = USEREVENT + 22
TETRIS_CLEAR = USEREVENT + 23
HARD_DROP_LINE = USEREVENT + 30
SOFT_DROP_LINE = USEREVENT + 31
GAMEOVER = USEREVENT + 50
LINE = USEREVENT + 100

# convert them to event object cause idk pygame is weird

EVENT_SINGLE_LINE = event.Event(SINGLE_LINE)
EVENT_DOUBLE_LINE = event.Event(DOUBLE_LINE)
EVENT_TRIPLE_LINE = event.Event(TRIPLE_LINE)
EVENT_TETRIS_LINE = event.Event(TETRIS_LINE)
EVENT_SPIN = event.Event(SPIN)
EVENT_MINI_SPIN = event.Event(MINI_SPIN)
EVENT_MINI_SINGLE_SPIN = event.Event(MINI_SINGLE_SPIN)
EVENT_SINGLE_SPIN = event.Event(SINGLE_SPIN)
EVENT_DOUBLE_SPIN = event.Event(DOUBLE_SPIN)
EVENT_TRIPLE_SPIN = event.Event(TRIPLE_SPIN)
EVENT_SINGLE_CLEAR = event.Event(SINGLE_CLEAR)
EVENT_DOUBLE_CLEAR = event.Event(DOUBLE_CLEAR)
EVENT_TRIPLE_CLEAR = event.Event(TRIPLE_CLEAR)
EVENT_TETRIS_CLEAR = event.Event(TETRIS_CLEAR)
EVENT_HARD_DROP_LINE = event.Event(HARD_DROP_LINE)
EVENT_SOFT_DROP_LINE = event.Event(SOFT_DROP_LINE)
EVENT_GAMEOVER = event.Event(GAMEOVER)
EVENT_LINE = event.Event(LINE)